services:
  webapp:
    image: vsrecorder/webapp:latest
    restart: always
    ports:
      - 3003:3003
    environment:
      - TZ=Asia/Tokyo
      - VSRECORDER_DOMAIN=${VSRECORDER_DOMAIN}
      - VSRECORDER_JWT_SECRET=${VSRECORDER_JWT_SECRET}
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - SAKURA_OBJECTSTORAGE_ACCESS_KEY_ID=${SAKURA_OBJECTSTORAGE_ACCESS_KEY_ID}
      - SAKURA_OBJECTSTORAGE_SECRET_ACCESS_KEY=${SAKURA_OBJECTSTORAGE_SECRET_ACCESS_KEY}
      - SAKURA_OBJECTSTORAGE_ENDPOINT=${SAKURA_OBJECTSTORAGE_ENDPOINT}
      - SAKURA_OBJECTSTORAGE_REGION=${SAKURA_OBJECTSTORAGE_REGION}
      - SAKURA_OBJECTSTORAGE_BUCKET_NAME=${SAKURA_OBJECTSTORAGE_BUCKET_NAME}
